### PR TITLE
docs: Add Sway By Example

### PR DESCRIPTION
**Pull request by calldelegation**

### CODE REVIEW

**Comment by calldelegation** [comment]
https://docs-9bwe0l3p8-fuel-labs.vercel.app/docs/sway-by-example-lib/

Change URL to without "-lib" and underscores

**Comment by calldelegation** [comment]
Breaking change log CI is fixed in this [PR](https://github.com/FuelLabs/docs-hub/pull/326)

**Review by Nazeeh21 — COMMENTED** [review]
Overall it looks good. But clicking on the summary page from the deployment, took me to 404 https://docs-qqeo5rzyg-fuel-labs.vercel.app/docs/sway-by-example-lib/summary/

**Review by Nazeeh21 — APPROVED** [review]
LGTM! 👍

**Review by laishawa — APPROVED** [review]
Changes are good to go!

**Pull request merged**
