### PR TITLE
chore: remove validation for ts api docs

### PR DESCRIPTION
**Pull request by Dhaiwat10**
This PR removes the validation in place for the TS SDK API docs since they have now been isolated in a different project on a different URL (https://github.com/FuelLabs/fuels-ts/pull/3237) and they are now only referenced from the 'main' TS SDK docs.

### CODE REVIEW

**Review by Nazeeh21 — DISMISSED** [review]

**Comment by petertonysmith94** [comment]
We're looking to approach this migration in a phased approach, so converted this to a draft.

**Review by danielbate — DISMISSED** [review]

**Review by petertonysmith94 — DISMISSED** [review]
It may be nice to keep the `API` link that opens a new window with the api-docs. I approve of these changes.

image

**Comment by Dhaiwat10** [comment]
@petertonysmith94 not really sure how to do that. @FuelLabs/devrel any ideas? 👀

**Comment by danielbate** [comment]
@petertonysmith94 @Dhaiwat10 I have included the link on the TS docs home page. We'd probably have to include it in the links json file but that'll probably break some kind of validation. IMO it should not block this work.

**Comment by danielbate** [comment]
@calldelegation @rishabhkeshan please let us know when you've had a chance to check this PR

**Comment by petertonysmith94** [comment]
https://vercel.com/fuel-labs/docs-hub/22k6WPftQk4vYpSDCd49NkuGpgzM#L361

> ERROR GETTING EXAMPLE CODE: Error: ENOENT: no such file or directory, open '/vercel/path0/docs/nightly/fuels-ts/apps/docs/nightly/fuels-ts/apps/docs/src/guide/contracts/snippets/cost-estimation.ts'

It looks like the final error is related to the relative path snippets introduced in #505 (which worked as expected locally when I tested it).

I believe the path referenced:
 '/vercel/path0/docs/nightly/fuels-ts/apps/docs/nightly/fuels-ts/apps/docs/src/guide/contracts/snippets/cost-estimation.ts'
 
 Should be:
 '/vercel/path0/docs/nightly/fuels-ts/apps/docs/src/guide/contracts/snippets/cost-estimation.ts'
 
 @calldelegation do you know what might be happening here?

**Comment by calldelegation** [comment]
@petertonysmith94 you are correct. @Dhaiwat10 and I were able to deduce down to the same issue yesterday which is the extra `docs/nightly/fuels-ts/apps` you are referring to.

Though it seems like an easy fix to simple trim the URL I am not sure on the top of my head but I can help investigate as soon as I have completed my higher priority tasks.

**Comment by petertonysmith94** [comment]
> @petertonysmith94 you are correct. @Dhaiwat10 and I were able to deduce down to the same issue yesterday which is the extra `docs/nightly/fuels-ts/apps` you are referring to.
> 
> Though it seems like an easy fix to simple trim the URL I am not sure on the top of my head but I can help investigate as soon as I have completed my higher priority tasks.

No rush - thanks @calldelegation 🙌🏼

**Review by calldelegation — APPROVED** [review]

**Review by calldelegation — APPROVED** [review]

**Review by danielbate — APPROVED** [review]

**Comment by petertonysmith94** [comment]
@Dhaiwat10 we also need to remove the [following line](https://github.com/FuelLabs/docs-hub/blob/dp/remove-ts-api-docs/scripts/update-nightly/updateSubmodules.mjs#L77) to ensure the automated versions doesn't check out our `docs` [branch](https://github.com/FuelLabs/fuels-ts/tree/docs).

**Review by petertonysmith94 — CHANGES_REQUESTED** [review]
@Dhaiwat10 we also need to remove the [following line](https://github.com/FuelLabs/docs-hub/blob/dp/remove-ts-api-docs/scripts/update-nightly/updateSubmodules.mjs#L77) to ensure the automated versions doesn't check out our `docs` [branch](https://github.com/FuelLabs/fuels-ts/tree/docs).

**Review by petertonysmith94 — APPROVED** [review]

**Review by calldelegation — APPROVED** [review]

**Review by danielbate — APPROVED** [review]

**Pull request merged**
